- block:
    - name: create ssl key
      openssl_privatekey:
        path: "{{ openstack_undercloud_ssl_key }}"
        size: "{{ openstack_undercloud_ssl_key_size }}"
        type: "{{ openstack_undercloud_ssl_key_type }}"
      register: _generate_ssl_key

    - name: check for certificate
      stat:
        path: "{{ openstack_undercloud_ssl_certificate }}"
      register: _ssl_certificate

    - name: create SSL certificiate
      command: >-
        openssl req -new -x509 -key "{{ openstack_undercloud_ssl_key }}"
        -out "{{ openstack_undercloud_ssl_certificate }}"
        -days 365
        -subj "/C=US/ST=NC/L=Raleigh/O=Red Hat/OU=QE/CN={{
        openstack_undercloud_public_host }}"
      when: _generate_ssl_key is changed or not _ssl_certificate.stat.exists
  delegate_to: localhost
