- name: register RHSM
  hosts: all
  pre_tasks:
    - name: create Network Manager connection
      command: nmcli c add type ethernet ifname eth1 con-name ethernet-eth1
      become: true
  roles:
    - role: oasis_roles.users_and_groups
    - role: greg_hellings.sudoers
    - role: oasis_roles.hostname
    - role: oasis_roles.rhsm
      when: ansible_distribution == 'RedHat'
  vars:
    hostname: "{{ ansible_hostname }}.openstack.local"
    users_and_groups_add_modify_users:
      - name: stack
    sudoers_no_password:
      - stack
    rhsm_username: "{{ lookup('env', 'OASIS_RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'OASIS_RHSM_PASSWORD') }}"
    rhsm_server_hostname: "{{ lookup('env', 'OASIS_RHSM_SERVER_HOSTNAME') }}"
    rhsm_pool_ids: "{{ lookup('env', 'OASIS_RHSM_POOL_IDS') }}"
    rhsm_repositories:
      disabled:
        - "*"
      enabled:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-rh-common-rpms
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-{{ openstack_version }}-rpms
